### ISSUE TITLE
Light transition

### ISSUE THREAD

**Issue by spripe** [haberda/light_automation#1]
Hi,

Thanks for a nice light automation :)
Would it be possible to add a feature for light transition?

Like; Light transition to a defined value in 10minutes? So it in a smooth way reach it defined goal value?

**Comment by haberda** [comment]
You can already do this! :)

Under

data:
  transition: XXX

where XXX is the time you want in seconds
You can specify anything under data that home-assistant allows for a light service call, including transition. Sorry if formatting sucks I'm on mobile.
