### ISSUE TITLE
Day of the week

### ISSUE THREAD

**Issue by leeandy1** [haberda/light_automation#3]
Is it possible to specify a day of the week for an automation to run?

I would like to limit one of the automations to only turn on a light on <onday and Tuesday at a set time?

**Comment by haberda** [comment]
Yes, you can use the native AppDaemon callback constraints to do this:

https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#callback-constraints

**Comment by leeandy1** [comment]
Thanks @haberda I will take a look. 

I'm new to Home Assistant and programming but will give it a shot.
