### ISSUE TITLE
Question: Will lights turn back on?

### ISSUE THREAD

**Issue by Gibby** [haberda/light_automation#4]
Say lights are defined to be on but are turned off, will this make sure they are turned back on?

**Comment by haberda** [comment]
This app does not actively run during the on->off period. If for some reason the lights turn off during the period, they stay off. 

However, the constraint options are monitored, and if the constraint is removed the lights will turn on if it is during the period. For example, if you have it track whether a person is home, if the person comes home after the 'on' time the lights will turn on.
